variables:
  K8S_NAMESPACE: self-service-suite
  APPLICATION_NAME: self-service-buckets
  CONTAINER_IMAGE_NAME: ${APPLICATION_NAME}
  CONTAINER_IMAGE: ${AWS_ECR_URL}/${CONTAINER_IMAGE_NAME}
  CONTAINER_IMAGE_TAGGED: ${CONTAINER_IMAGE}:${CI_COMMIT_SHORT_SHA}

build-job:
  stage: build
  before_script:
    - >
      aws ecr create-repository --repository-name ${CONTAINER_IMAGE_NAME}
      || echo "Repository might have already existed"

  script:
    - docker build -t ${CONTAINER_IMAGE_TAGGED} .
    - docker push ${CONTAINER_IMAGE_TAGGED}
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

deploy-job:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - kubectl config use-context eks-internal-public/gitlab-agent-for-kubernetes:eks-internal-public
    - kubectl create namespace $K8S_NAMESPACE --dry-run=client -o yaml | kubectl apply -f -
    - kubectl config set-context --current --namespace=$K8S_NAMESPACE
    # TODO: use ESO instead of CICD env
    - kubectl create secret generic self-service-buckets-env --from-env-file=$ENV --dry-run=client -o yaml | kubectl apply -f -
    - envsubst < kubernetes_manifest.yml | kubectl apply -f -
